# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: DBA
google_analytics: DBA
title: "DBA HANDBOOK"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "DBA HANDBOOK"

description: Stylish Jekyll Theme
author:
  name: zhu00yu
  email: zhu00yu@aliyun.com
  github: zhu00yu
  # twitter: dbtek
  # pinterest: asd123
  # linkedin: asd123
  bio: 天下大事必作于细，天下难事必作于易。<br/>一切跪在积累！
  # email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH: /DBA-Handbook

plugins:
  - jekyll-paginate
